// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostPilot.Api.Data;

#nullable disable

namespace PostPilot.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223215653_AddInstagramMediaTagsJson")]
    partial class AddInstagramMediaTagsJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostPilot.Api.Entities.AiVoiceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BannedWords")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DoRules")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DontRules")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExamplePosts")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AiVoiceProfiles");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.ConnectedInstagramAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IgBusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MetaConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MetaConnectionId", "IgBusinessId")
                        .IsUnique();

                    b.ToTable("ConnectedInstagramAccounts");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.ConnectedPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MetaConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MetaConnectionId", "PageId")
                        .IsUnique();

                    b.ToTable("ConnectedPages");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.MetaConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MetaConnections");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.MetaOAuthState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TempAccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("MetaOAuthStates");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExternalPostId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalPostUrl")
                        .HasColumnType("text");

                    b.Property<string>("FacebookStoryMediaId")
                        .HasColumnType("text");

                    b.Property<string>("InstagramCarouselCreationId")
                        .HasColumnType("text");

                    b.Property<string>("InstagramChildCreationIds")
                        .HasColumnType("text");

                    b.Property<string>("InstagramCreationId")
                        .HasColumnType("text");

                    b.Property<string>("InstagramMediaTagsJson")
                        .HasColumnType("text");

                    b.Property<int?>("InstagramMediaType")
                        .HasColumnType("integer");

                    b.Property<string>("InstagramUserTags")
                        .HasColumnType("text");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Feed");

                    b.Property<int>("ProcessingPollCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduleArn")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectedThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetInstagramAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetPageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TargetInstagramAccountId");

                    b.HasIndex("TargetPageId");

                    b.HasIndex("Status", "NextRetryAt");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.PostMediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "Order");

                    b.ToTable("PostMediaItems");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.ConnectedInstagramAccount", b =>
                {
                    b.HasOne("PostPilot.Api.Entities.MetaConnection", "MetaConnection")
                        .WithMany("InstagramAccounts")
                        .HasForeignKey("MetaConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaConnection");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.ConnectedPage", b =>
                {
                    b.HasOne("PostPilot.Api.Entities.MetaConnection", "MetaConnection")
                        .WithMany("Pages")
                        .HasForeignKey("MetaConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaConnection");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.Post", b =>
                {
                    b.HasOne("PostPilot.Api.Entities.ConnectedInstagramAccount", "TargetInstagramAccount")
                        .WithMany()
                        .HasForeignKey("TargetInstagramAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PostPilot.Api.Entities.ConnectedPage", "TargetPage")
                        .WithMany()
                        .HasForeignKey("TargetPageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetInstagramAccount");

                    b.Navigation("TargetPage");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.PostMediaItem", b =>
                {
                    b.HasOne("PostPilot.Api.Entities.Post", "Post")
                        .WithMany("MediaItems")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.MetaConnection", b =>
                {
                    b.Navigation("InstagramAccounts");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("PostPilot.Api.Entities.Post", b =>
                {
                    b.Navigation("MediaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
